# **Kegiatan Modul 4**

**Poin penilaian :**

* Tingkat kesesuaian program
* Kesesuaian step preprocessing dan pemodelan
* Penjelasan yang tepat
* Kerapian kode program
* Tidak ada error

In [0]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

### Tentang dataset

Kita akan menggunakan data telekomunikasi untuk memprediksi churn pelanggan. Ini adalah data pelanggan historis di mana setiap baris mewakili satu pelanggan. Data ini relatif mudah dipahami, dan Anda dapat mengungkap wawasan yang dapat Anda gunakan segera. Biasanya lebih murah untuk mempertahankan pelanggan daripada membeli yang baru, jadi fokus analisis ini adalah untuk memprediksi pelanggan yang akan tinggal di perusahaan.

Kumpulan data ini menyediakan info untuk membantu Anda memprediksi perilaku mempertahankan pelanggan. Anda dapat menganalisis semua data pelanggan yang relevan dan mengembangkan program retensi pelanggan yang terfokus.

Kumpulan data mencakup informasi tentang:

- Pelanggan yang pergi dalam sebulan terakhir - kolom ini disebut Churn
- Layanan yang telah ditandatangani oleh setiap pelanggan - telepon, banyak saluran, internet, keamanan online, cadangan online, perlindungan perangkat, dukungan teknis, dan streaming TV dan film
- Informasi akun pelanggan - berapa lama mereka menjadi pelanggan, kontrak, metode pembayaran, penagihan tanpa kertas, biaya bulanan, dan total biaya
- Info demografis tentang pelanggan - jenis kelamin, rentang usia, dan jika mereka memiliki mitra dan tanggungan

### **Download the Telco Churn data**

Telco Churn adalah file data hipotetis yang menyangkut upaya perusahaan telekomunikasi untuk mengurangi turnover di basis pelanggannya. Setiap kasing sesuai dengan pelanggan terpisah dan mencatat berbagai informasi penggunaan layanan dan demografis. Sebelum Anda dapat bekerja dengan data, Anda harus menggunakan URL untuk mendapatkan ChurnData.csv.

Untuk mengunduh data, kami akan menggunakan `!wget` untuk mengunduhnya dari IBM Object Storage.

In [0]:
!wget -O ChurnData.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/ChurnData.csv

--2020-02-11 07:26:41--  https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/ChurnData.csv
Resolving s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)... 67.228.254.196
Connecting to s3-api.us-geo.objectstorage.softlayer.net (s3-api.us-geo.objectstorage.softlayer.net)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36144 (35K) [text/csv]
Saving to: ‘ChurnData.csv’

ChurnData.csv       100%[===================>]  35.30K  --.-KB/s    in 0.01s   

2020-02-11 07:26:41 (2.88 MB/s) - ‘ChurnData.csv’ saved [36144/36144]



## **SOAL-SOAL**

Kegiatan 1. **5 poin**

Load dataset dari file csv.

In [0]:
# TULIS CODE ANDA DISINI



```
# Output tabel
```


<img src = "https://i.ibb.co/Ss0mQk3/1.png" align = "center">

### **Data pre-processing and selection**

Kegiatan 2. **10 poin**

Mari kita pilih beberapa fitur untuk pemodelan dalam kasus ini kita akan memilih fitur `tenure, age, address, income, ed, employ, equip, callcard, wireless, churn`. 

Kita juga mengubah tipe data target menjadi bilangan bulat, sebab merupakan persyaratan oleh algoritma pembelajaran scikit:

In [0]:
# TULIS CODE ANDA DISINI



```
# Output tabel
```


<img src = "https://i.ibb.co/zmc2YP0/2.png" align = "center">

Kegiatan 3. **5 poin**

Berapa ukuran dataset yang anda miliki sekarang? (row, coloumn)



```
# Output

  (200, 10)
```



In [0]:
# TULIS CODE ANDA DISINI

Kegiatan 4. **5 poin**

Tentukan x, dan y untuk dataset kita: 

**HINT!** ubah ke numpy array



```
# Output

  array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])
```



In [0]:
# TULIS CODE ANDA DISINI



```
# Output

  array([1, 1, 0, 0, 0])
```



In [0]:
# TULIS CODE ANDA DISINI

Kegiatan 5. **5 poin**

Normalisasi dataset:

**HINT** library preprocessing dari sklearn.



```
# Output

  array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])
```



In [0]:
# TULIS CODE ANDA DISINI

Kegiatan 6. **5 poin**

Selanjutnya kita akan membagi dataset Anda menjadi train dan test set dengan porsi perbandingan 80:20 dan `random_state`tak didefinisikan:



```
# Output

Train set: (160, 7) (160,)
Test set: (40, 7) (40,)
```



In [0]:
# TULIS CODE ANDA DISINI



--- 
Perhatikan materi modul 4 bagian **Modeling (Logistic Regression with Scikit-learn)**
---


---





Kegiatan 7. **30 poin per model**

*POIN MAKSIMAL 60*

Buatlah 2 model Logistic Regression baru untuk dataset yang sama, tetapi kali ini, gunakan nilai __solver__ dan __regularisasi__ yang berbeda? Apa nilai __logLoss__ baru?

### *Ikuti step pengerjaan dibawah:*

Penilaian mulai dari:

* Membuat model

* Melakukan dan menampilkan hasil  prediksi data test `yhat dan yhat_prob`

* Evaluation menggunakan confussion matrix.

* Tampilkan hasil `classification_report`

* Tampilkan hasil `log_loss`

* Jelaskan semua hal yang anda menggerti atau hal yang anda dapatkan dalam modul ini.

### **BONUS 5 POIN jika semua kegiatan dapat diselesaikan dengan baik dan dapat menjelaskan semua kegiatan dengan fasih.**